"use client";

import { useState } from "react";
import { useAuth } from "@/contexts/auth-context";
import DashboardLayout from "@/components/layout/dashboard-layout";
import {
  FileBarChart,
  Download,
  Calendar,
  Filter,
  FileText,
  TrendingUp,
  Users,
  Scale,
  AlertCircle,
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

export default function ReportsPage() {
  const { user, token } = useAuth();
  const [reportType, setReportType] = useState("crime-statistics");
  const [dateRange, setDateRange] = useState("month");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("");
  const [officerFilter, setOfficerFilter] = useState("");

  const handleGenerate = async (format: "csv" | "json" | "pdf" | "excel") => {
    setIsGenerating(true);
    setError("");

    try {
      // Fetch report data from API
      const response = await fetch("/api/reports", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          reportType,
          dateRange,
          startDate,
          endDate,
          category:
            reportType === "crime-statistics" ? categoryFilter : undefined,
          officerId:
            reportType === "officer-performance" ? officerFilter : undefined,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate report");
      }

      const reportData = await response.json();

      // Generate file based on format
      switch (format) {
        case "csv":
          downloadCSV(reportData);
          break;
        case "json":
          downloadJSON(reportData);
          break;
        case "pdf":
          downloadPDF(reportData);
          break;
        case "excel":
          downloadExcel(reportData);
          break;
      }
    } catch (error) {
      console.error("Report generation error:", error);
      setError("Failed to generate report. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPDF = (reportData: any) => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.text(`${reportType.replace(/-/g, " ").toUpperCase()} REPORT`, 14, 20);

    // Metadata
    doc.setFontSize(10);
    doc.text(
      `Generated: ${new Date(reportData.generatedAt).toLocaleString()}`,
      14,
      30,
    );
    doc.text(
      `Generated By: ${reportData.generatedBy.name} (${reportData.generatedBy.serviceNumber})`,
      14,
      35,
    );
    doc.text(
      `Date Range: ${new Date(reportData.dateRange.start).toLocaleDateString()} - ${new Date(reportData.dateRange.end).toLocaleDateString()}`,
      14,
      40,
    );

    // Summary Stats
    if (reportData.data.summary) {
      doc.setFontSize(12);
      doc.text("Summary Statistics", 14, 50);
      doc.setFontSize(10);

      let yPos = 55;
      Object.entries(reportData.data.summary).forEach(([key, value]) => {
        if (typeof value === "number") {
          doc.text(`${key}: ${value}`, 14, yPos);
          yPos += 5;
        }
      });
    }

    // Table Data
    let tableStartY = reportData.data.summary ? 80 : 50;

    if (reportType === "crime-statistics" && reportData.data.cases) {
      autoTable(doc, {
        startY: tableStartY,
        head: [["OB Number", "Title", "Category", "Status", "Station"]],
        body: reportData.data.cases
          .slice(0, 50)
          .map((c: any) => [
            c.obNumber,
            c.title.substring(0, 30) + (c.title.length > 30 ? "..." : ""),
            c.category,
            c.status,
            c.station.name,
          ]),
      });
    } else if (
      reportType === "officer-performance" &&
      reportData.data.officers
    ) {
      autoTable(doc, {
        startY: tableStartY,
        head: [
          [
            "Name",
            "Service No",
            "Cases Reported",
            "Cases Assigned",
            "Traffic",
            "Total",
          ],
        ],
        body: reportData.data.officers.map((o: any) => [
          o.name,
          o.serviceNumber,
          o.casesReported,
          o.casesAssigned,
          o.trafficOffenses,
          o.totalActivity,
        ]),
      });
    } else if (reportType === "traffic-offenses" && reportData.data.offenses) {
      autoTable(doc, {
        startY: tableStartY,
        head: [["Offense No", "Vehicle", "Type", "Fine", "Paid"]],
        body: reportData.data.offenses
          .slice(0, 50)
          .map((o: any) => [
            o.offenseNumber,
            o.vehicleReg,
            o.offenseType,
            `KES ${o.fineAmount || 0}`,
            o.isPaid ? "Yes" : "No",
          ]),
      });
    } else if (reportType === "court-cases" && reportData.data.courtFiles) {
      autoTable(doc, {
        startY: tableStartY,
        head: [["Case Number", "Court", "OB Number", "Status"]],
        body: reportData.data.courtFiles
          .slice(0, 50)
          .map((c: any) => [
            c.caseNumber,
            c.courtName,
            c.case.obNumber,
            c.status,
          ]),
      });
    }

    doc.save(`${reportType}-report-${new Date().getTime()}.pdf`);
  };

  const downloadExcel = (reportData: any) => {
    const wb = XLSX.utils.book_new();

    // Summary sheet
    const summaryData = [
      ["Report Type", reportType.replace(/-/g, " ").toUpperCase()],
      ["Generated", new Date(reportData.generatedAt).toLocaleString()],
      [
        "Generated By",
        `${reportData.generatedBy.name} (${reportData.generatedBy.serviceNumber})`,
      ],
      [
        "Date Range",
        `${new Date(reportData.dateRange.start).toLocaleDateString()} - ${new Date(reportData.dateRange.end).toLocaleDateString()}`,
      ],
      [],
    ];

    if (reportData.data.summary) {
      summaryData.push(["Summary Statistics"], []);
      Object.entries(reportData.data.summary).forEach(([key, value]) => {
        if (typeof value === "number") {
          summaryData.push([key, `$${value}`]);
        }
      });
    }

    const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");

    // Data sheet
    if (reportType === "crime-statistics" && reportData.data.cases) {
      const dataWs = XLSX.utils.json_to_sheet(
        reportData.data.cases.map((c: any) => ({
          "OB Number": c.obNumber,
          Title: c.title,
          Category: c.category,
          Status: c.status,
          Priority: c.priority,
          Station: c.station.name,
          "Reported By": `${c.reportedBy.rank} ${c.reportedBy.firstName} ${c.reportedBy.lastName}`,
          Date: new Date(c.createdAt).toLocaleDateString(),
        })),
      );
      XLSX.utils.book_append_sheet(wb, dataWs, "Cases");
    } else if (
      reportType === "officer-performance" &&
      reportData.data.officers
    ) {
      const dataWs = XLSX.utils.json_to_sheet(reportData.data.officers);
      XLSX.utils.book_append_sheet(wb, dataWs, "Officer Performance");
    } else if (reportType === "traffic-offenses" && reportData.data.offenses) {
      const dataWs = XLSX.utils.json_to_sheet(
        reportData.data.offenses.map((o: any) => ({
          "Offense Number": o.offenseNumber,
          Vehicle: o.vehicleReg,
          Driver: o.driverName,
          Type: o.offenseType,
          Location: o.location,
          Fine: o.fineAmount || 0,
          Paid: o.isPaid ? "Yes" : "No",
          Officer: `${o.officer.rank} ${o.officer.firstName} ${o.officer.lastName}`,
          Date: new Date(o.createdAt).toLocaleDateString(),
        })),
      );
      XLSX.utils.book_append_sheet(wb, dataWs, "Traffic Offenses");
    } else if (reportType === "court-cases" && reportData.data.courtFiles) {
      const dataWs = XLSX.utils.json_to_sheet(
        reportData.data.courtFiles.map((c: any) => ({
          "Case Number": c.caseNumber,
          Court: c.courtName,
          "OB Number": c.case.obNumber,
          "Case Title": c.case.title,
          Status: c.status,
          "Filing Date": new Date(c.filingDate).toLocaleDateString(),
          "Filed By": `${c.filedBy.rank} ${c.filedBy.firstName} ${c.filedBy.lastName}`,
        })),
      );
      XLSX.utils.book_append_sheet(wb, dataWs, "Court Cases");
    }

    XLSX.writeFile(wb, `${reportType}-report-${new Date().getTime()}.xlsx`);
  };

  const downloadCSV = (reportData: any) => {
    let csvContent = "";

    csvContent += `Report Type: ${reportType}\n`;
    csvContent += `Generated: ${new Date(reportData.generatedAt).toLocaleString()}\n`;
    csvContent += `Generated By: ${reportData.generatedBy.name} (${reportData.generatedBy.serviceNumber})\n`;
    csvContent += `Date Range: ${new Date(reportData.dateRange.start).toLocaleDateString()} - ${new Date(reportData.dateRange.end).toLocaleDateString()}\n\n`;

    if (reportType === "crime-statistics" && reportData.data.cases) {
      csvContent +=
        "OB Number,Title,Category,Status,Priority,Station,Reported By,Date\n";
      reportData.data.cases.forEach((c: any) => {
        csvContent += `${c.obNumber},"${c.title}",${c.category},${c.status},${c.priority},${c.station.name},"${c.reportedBy.rank} ${c.reportedBy.firstName} ${c.reportedBy.lastName}",${new Date(c.createdAt).toLocaleDateString()}\n`;
      });
    } else if (
      reportType === "officer-performance" &&
      reportData.data.officers
    ) {
      csvContent +=
        "Name,Service Number,Cases Reported,Cases Assigned,Traffic Offenses,Total Activity\n";
      reportData.data.officers.forEach((o: any) => {
        csvContent += `"${o.name}",${o.serviceNumber},${o.casesReported},${o.casesAssigned},${o.trafficOffenses},${o.totalActivity}\n`;
      });
    } else if (reportType === "traffic-offenses" && reportData.data.offenses) {
      csvContent +=
        "Offense Number,Vehicle,Driver,Type,Location,Fine,Paid,Officer,Date\n";
      reportData.data.offenses.forEach((o: any) => {
        csvContent += `${o.offenseNumber},${o.vehicleReg},"${o.driverName}",${o.offenseType},${o.location},${o.fineAmount || 0},${o.isPaid ? "Yes" : "No"},"${o.officer.rank} ${o.officer.firstName} ${o.officer.lastName}",${new Date(o.createdAt).toLocaleDateString()}\n`;
      });
    } else if (reportType === "court-cases" && reportData.data.courtFiles) {
      csvContent +=
        "Case Number,Court,OB Number,Case Title,Status,Filing Date,Filed By\n";
      reportData.data.courtFiles.forEach((c: any) => {
        csvContent += `${c.caseNumber},"${c.courtName}",${c.case.obNumber},"${c.case.title}",${c.status},${new Date(c.filingDate).toLocaleDateString()},"${c.filedBy.rank} ${c.filedBy.firstName} ${c.filedBy.lastName}"\n`;
      });
    }

    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${reportType}-report-${new Date().getTime()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const downloadJSON = (reportData: any) => {
    const blob = new Blob([JSON.stringify(reportData, null, 2)], {
      type: "application/json",
    });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${reportType}-report-${new Date().getTime()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout>
      <div className="p-6 ">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-white">Reports</h1>
          <p className="text-gray-400 mt-1">
            Generate and download comprehensive reports
          </p>
        </div>

        {/* Error Message */}
        {error && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-4 mb-6 flex items-start gap-3">
            <AlertCircle className="h-5 w-5 text-red-400 flex-shrink-0 mt-0.5" />
            <p className="text-red-200">{error}</p>
          </div>
        )}

        {/* Report Types Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <button
            onClick={() => setReportType("crime-statistics")}
            className={`p-6 rounded-xl border-2 transition-all ${
              reportType === "crime-statistics"
                ? "bg-blue-600 border-blue-500"
                : "bg-white/5 border-white/10 hover:bg-white/10"
            }`}
          >
            <FileBarChart className="h-8 w-8 text-blue-400 mb-3" />
            <h3 className="font-semibold text-white mb-1">Crime Statistics</h3>
            <p className="text-xs text-gray-400">Cases by category & status</p>
          </button>

          <button
            onClick={() => setReportType("officer-performance")}
            className={`p-6 rounded-xl border-2 transition-all ${
              reportType === "officer-performance"
                ? "bg-green-600 border-green-500"
                : "bg-white/5 border-white/10 hover:bg-white/10"
            }`}
          >
            <Users className="h-8 w-8 text-green-400 mb-3" />
            <h3 className="font-semibold text-white mb-1">
              Officer Performance
            </h3>
            <p className="text-xs text-gray-400">Cases handled & metrics</p>
          </button>

          <button
            onClick={() => setReportType("traffic-offenses")}
            className={`p-6 rounded-xl border-2 transition-all ${
              reportType === "traffic-offenses"
                ? "bg-yellow-600 border-yellow-500"
                : "bg-white/5 border-white/10 hover:bg-white/10"
            }`}
          >
            <TrendingUp className="h-8 w-8 text-yellow-400 mb-3" />
            <h3 className="font-semibold text-white mb-1">Traffic Report</h3>
            <p className="text-xs text-gray-400">Offenses & fines collected</p>
          </button>

          <button
            onClick={() => setReportType("court-cases")}
            className={`p-6 rounded-xl border-2 transition-all ${
              reportType === "court-cases"
                ? "bg-purple-600 border-purple-500"
                : "bg-white/5 border-white/10 hover:bg-white/10"
            }`}
          >
            <Scale className="h-8 w-8 text-purple-400 mb-3" />
            <h3 className="font-semibold text-white mb-1">Court Cases</h3>
            <p className="text-xs text-gray-400">Filed cases & verdicts</p>
          </button>
        </div>

        {/* Report Configuration */}
        <div className="bg-white/10 rounded-xl border border-white/20 p-6 mb-6">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
            <Filter className="h-5 w-5 text-blue-400" />
            Report Configuration
          </h2>

          <div className="space-y-4">
            {/* Date Range */}
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Date Range
              </label>
              <Select value={dateRange} onValueChange={setDateRange}>
                <SelectTrigger className="bg-white/5 border-white/10 text-white w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-slate-800 border-white/10">
                  <SelectItem value="today" className="text-white">
                    Today
                  </SelectItem>
                  <SelectItem value="week" className="text-white">
                    This Week
                  </SelectItem>
                  <SelectItem value="month" className="text-white">
                    This Month
                  </SelectItem>
                  <SelectItem value="quarter" className="text-white">
                    This Quarter
                  </SelectItem>
                  <SelectItem value="year" className="text-white">
                    This Year
                  </SelectItem>
                  <SelectItem value="custom" className="text-white">
                    Custom Range
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Custom Date Range */}
            {dateRange === "custom" && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Start Date
                  </label>
                  <Input
                    type="date"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full bg-white/5 border-white/10 text-white"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    End Date
                  </label>
                  <Input
                    type="date"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full bg-white/5 border-white/10 text-white"
                  />
                </div>
              </div>
            )}

            {/* Additional Filters based on Report Type */}
            {reportType === "crime-statistics" && (
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Category Filter (Optional)
                </label>
                <Select
                  value={categoryFilter}
                  onValueChange={setCategoryFilter}
                >
                  <SelectTrigger className="bg-white/5 border-white/10 text-white w-full">
                    <SelectValue placeholder="All Categories" />
                  </SelectTrigger>
                  <SelectContent className="bg-slate-800 border-white/10">
                    <SelectItem value="all" className="text-white">
                      All Categories
                    </SelectItem>
                    <SelectItem value="THEFT" className="text-white">
                      Theft
                    </SelectItem>
                    <SelectItem value="ASSAULT" className="text-white">
                      Assault
                    </SelectItem>
                    <SelectItem value="ROBBERY" className="text-white">
                      Robbery
                    </SelectItem>
                    <SelectItem value="MURDER" className="text-white">
                      Murder
                    </SelectItem>
                    <SelectItem value="TRAFFIC" className="text-white">
                      Traffic
                    </SelectItem>
                    <SelectItem value="DOMESTIC" className="text-white">
                      Domestic
                    </SelectItem>
                    <SelectItem value="FRAUD" className="text-white">
                      Fraud
                    </SelectItem>
                    <SelectItem value="CYBERCRIME" className="text-white">
                      Cybercrime
                    </SelectItem>
                    <SelectItem value="NARCOTICS" className="text-white">
                      Narcotics
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}

            {reportType === "officer-performance" &&
              user?.role !== "CONSTABLE" && (
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Officer Filter (Optional)
                  </label>
                  <Input
                    type="text"
                    value={officerFilter}
                    onChange={(e) => setOfficerFilter(e.target.value)}
                    placeholder="Leave empty for all officers"
                    className="bg-white/5 border-white/10 text-white placeholder-gray-500"
                  />
                </div>
              )}
          </div>
        </div>

        {/* Export Options */}
        <div className="bg-white/10 rounded-xl border border-white/20 p-6 mb-6">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
            <Download className="h-5 w-5 text-green-400" />
            Export Options
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <button
              onClick={() => handleGenerate("pdf")}
              disabled={isGenerating}
              className="flex items-center justify-center gap-2 p-4 bg-red-600 hover:bg-red-700 rounded-lg transition-colors disabled:opacity-50"
            >
              <FileText className="h-5 w-5" />
              <span>Export PDF</span>
            </button>

            <button
              onClick={() => handleGenerate("excel")}
              disabled={isGenerating}
              className="flex items-center justify-center gap-2 p-4 bg-green-600 hover:bg-green-700 rounded-lg transition-colors disabled:opacity-50"
            >
              <FileBarChart className="h-5 w-5" />
              <span>Export Excel</span>
            </button>

            <button
              onClick={() => handleGenerate("csv")}
              disabled={isGenerating}
              className="flex items-center justify-center gap-2 p-4 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors disabled:opacity-50"
            >
              <FileText className="h-5 w-5" />
              <span>Export CSV</span>
            </button>

            <button
              onClick={() => handleGenerate("json")}
              disabled={isGenerating}
              className="flex items-center justify-center gap-2 p-4 bg-purple-600 hover:bg-purple-700 rounded-lg transition-colors disabled:opacity-50"
            >
              <FileText className="h-5 w-5" />
              <span>Export JSON</span>
            </button>
          </div>

          {isGenerating && (
            <div className="mt-4 flex items-center justify-center gap-3 text-gray-300">
              <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
              <span>Generating report...</span>
            </div>
          )}
        </div>

        {/* Report Preview Info */}
        <div className="bg-blue-500/10 border border-blue-500/30 rounded-xl p-6">
          <h3 className="font-semibold text-white mb-2 flex items-center gap-2">
            <FileText className="h-5 w-5 text-blue-400" />
            Report Preview
          </h3>
          <div className="text-sm text-gray-300 space-y-2">
            <p>
              <strong>Report Type:</strong>{" "}
              {reportType.replace(/-/g, " ").toUpperCase()}
            </p>
            <p>
              <strong>Date Range:</strong> {dateRange.toUpperCase()}
            </p>
            <p>
              <strong>Generated By:</strong> {user?.rank} {user?.firstName}{" "}
              {user?.lastName}
            </p>
            <p>
              <strong>Station:</strong> {user?.station?.name || "All Stations"}
            </p>
            <p className="text-xs text-gray-400 mt-4">
              ✅ Reports include full data with summary statistics
            </p>
            <p className="text-xs text-gray-400">
              ✅ All data is filtered based on your access level and permissions
            </p>
            <p className="text-xs text-green-400 mt-2">
              🎉 Real report generation is now active - click any export button
              to download!
            </p>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
